language: java
jdk: openjdk8
if: tag IS present
branches:
  only:
  - master
  - "/^test-.*$/"
  - "/^deploy-.*$/"
  - "/^v[0-9].*$/"

env:
  global:
    secure: "Cnydqp5SKg5hom/nLgKlxxzcKJ/zeinU44jOK3yau5FLITuNk6qbmnAhwIoVx78K25OLgfHyCC3B3UP39oIsxAw+ag65Cj/okfS9shkNPWdRdCctIzcQlQGwvWok9x8ivOVts0iyNJpu1u55vB7iKJTueHOkbTPM+K9iIIowRf4kXbOeayZJS7pz1dBPVeAf55XnavKBmd2LxEILpErL5fuPBqmiK5u8kC8VFUzaF6Yrrwj3glX/vRJ6PWx+aQGyc5VYWOOP8jixeTr4blf/b59kC1vCNwkaDkIxgjXckpo2rqRAnofuXfpvNPFALu1weofOjUU1tOd+bOXS9d8KWS8sCj6BeRlCPdUqU0lNRdqGqDs70XKAh2juIQbaLvKRj8S8uQxkcnazhSdTvnOkOj+bMcmGI09ueUWM4jnoKG5O6Wm+yJMtraFQSDFLTmkaXS2eVBW4/2+Xe8mx0v1qDWMh9lTe77jSAfyaRS8ny3tMnclOktwngjP1nVyPbpDFkSe8itcpLxbpUAXrDBnx6z2L00hhigbGy16fC4jQPahimnSDqu5S7eAasdFhP46sAHWNX4wZpuZc2yz2VpN4eN+UKJTQXprvJutWnutgRTQP8p7K6amPC2XKwW3ZdfcceSjLftBKRwO/3G3lC6E7UybHCb9yiJqdjrXnZzTI808="

notifications:
  slack: grupprop22:xEQjUsvIeCpH44ZJwrmMByS2

before_deploy:
  - mvn package -DskipTests=true -Djar.finalName=compressor-$TRAVIS_TAG
  - mkdir -p ~/.m2
  - echo "<settings><servers><server><id>github</id><username>Leixb</username><password>${GH_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
  - mvn deploy -Dregistry=https://maven.pkg.github.com/Leixb -Dtoken=$GH_TOKEN

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SUWnKwJ62Jdeuec/UATckXNqmb6Ztzc00HtKp28cJtGbYttOdbwyGsu6igJ2FmDFa9QMPNNTwScei/lWBpGY76KJqUfPcWDr1Tpq4E8f+Ys1qTOr9AzRu9ANAgkTjP3H8+uLE8PJZIwUxAfo0cGu/f650mK3p05glmQ1vG5Y0KuSZc0V3KqicTO4cB2/RT4g/oDLtfi8fkSJXp7kqFW27Yyan+rq2QuNE6Ib+NX19CrFyM2pxfC986NHBwPXMMqWGJCe6BIVkML+ESXEwlu02GrVCfzYyZxA0qTozOM1v83nwy+MXn3pwCY3AjEhVP/msDSnyE4b+eJq/5MJhw+s9jUI4rP1nFRi6z25cKvE9g9uy5V8n6OoVKlTc11TnEcSDqJmiTY2S6pCngrEOsPElEXHCoffAEm1QL5uDL7LjrPyF4BE2+NOqPUJ+hiAB2P3x03l9dZHa2nsXrmpcbVaRwODsnHU6x5Wp4bArZbD4gbHJz9bANuK2xyt2YYANBho8IAQGOppyL1WCzX4EsCByCdrBVuG7+jtPckwrqliANsRVLRyoG9+Cs38ALNmh7os6kpVUb7ZMMsECmKWKE8ydIwz+kbSo+gnADLpJhyvorJxZe/eZA668uOoTqlXGiBGzxs3MvjIHYDVPg9FTZVlhHgLD2b896OXbdgdkgZFkWM=
  file: target/compressor-$TRAVIS_TAG.jar
  on:
    repo: Leixb/Compressor_PROP
    branch: master
    tags: true
