@startuml

skinparam classAttributeIconSize 0

title Diagrama de classes IO

package Domini {
    class IO {
    }
    class Char
    class readerChar as "reader" {
        +reader(filename)
    }
    class writerChar as "writer" {
        +writer(filename)
    }
    class Byte
    class readerByte as "reader" {
        +reader(filename)
    }
    class writerByte as "writer" {
        +writer(filename)
    }
    class Bit
    class readerBit as "reader" {
        - in : BufferedInputStream
        - buffer : int
        - n : int
        +reader(String filename)
        -void fill()
        +boolean read()
        -int readMask(int mask)
        +byte readByte()
        +char readChar()
        +int readInt()
        +BitSetL readBitSet()
        +void close()
    }
    class writerBit as "writer" {
        - out : BufferedOutputStream
        - buffer : int
        - n : int
        +writer(String filename)
        +write(bit)
        +write(bs)
        +write(b)
        +write(c)
        +write(num)
        -writeMask(int num, int mask)
        -clear()
        +flush()
        +close()
    }

    class BufferedInputStream
    class BufferedOutputStream
    class FileInputStream
    class FileOutputStream

    FileOutputStream <|-- writerChar
    FileInputStream <|-- readerChar
    BufferedOutputStream <|-- writerByte
    BufferedInputStream <|-- readerByte


    IO *-- Char
    IO *-- Byte
    IO *-- Bit
    Char *-- writerChar
    Char *-- readerChar
    Byte *-- writerByte
    Byte *-- readerByte
    Bit *-- readerBit
    Bit *-- writerBit
}


@enduml
