name: make (JDK 1.8.0)

on:
  push:
    paths-ignore:
    - 'doc/**'
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1.1.0
      with:
        fetch-depth: 1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build
      run: make build
    - name: build_jar
      run: make jar
    - name: JUnit test
      run: make run_test
